import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";

const LexendDecaFont = Lexend_Deca({
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={LexendDecaFont.className}>{children}</body>
    </html>
  );
}
